include:
  - project: 'just-ci/templates'
    file: 'templates/container/python.yml'
    ref: 'v5.2.0'

variables:
  PYTHON_PACKAGE: ned
  GITLAB_RECOMMENDED_AUTO_FIX: "true"
  BANDIT_SKIP_CHECK: "B311"

python:bandit:
  allow_failure: true

grype:
  allow_failure: true

ned:netflows:
  stage: test
  variables:
    LOG_LEVEL: info
    NED_AMOUNT_RECORDS: 10
  script:
    - ned --type netflow

ned:dns:
  stage: test
  variables:
    LOG_LEVEL: info
    NED_AMOUNT_RECORDS: 10
  script:
    - ned --type dns
