include:
  - project: 'notno/ci-templates'
    file: 'templates/python.yml'
    ref: 'beta'

variables:
  PYTHON_PACKAGE: ned
  GITLAB_RECOMMENDED_AUTO_FIX: "true"

python:bandit:
  variables:
    SKIP_CHECK: B311
