include:
  - project: 'notno/ci-templates'
    file: 'templates/python-docker.yml'
    ref: 'beta'

variables:
  PYTHON_PACKAGE: ned
  GITLAB_RECOMMENDED_AUTO_FIX: "true"
  BANDIT_SKIP_CHECK: "B311"

python:bandit:
  allow_failure: true

grype:
  allow_failure: true
